export const CREATE_SHOW_SUCESS = "CREATE_SHOW_SUCESS";
export const CREATE_SHOW_FAIL = "CREATE_SHOW_FAIL";
export const FETCH_SHOW_SUCESS = "CREATE_SHOW_SUCESS";
export const FETCH_SHOW_FAIL = "FETCH_SHOW_FAIL";
