export const CREATE_THEATER_SUCESS = "CREATE_THEATER_SUCESS";
export const CREATE_THEATER_FAIL = "CREATE_THEATER_FAIL";
export const FETCH_THEATER_SUCESS = "CREATE_THEATER_SUCESS";
export const FETCH_THEATER_FAIL = "FETCH_THEATER_FAIL";
