spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlinebookingsystem?useSSL=false
    username: root
    password: gayatri


  jpa:
    hibernate:
      ddl_auto: update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL8Dialect