spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_sql?useSSL=false
    username: sqlUser
    password: sqlPassword



  jpa:
    hibernate:
      ddl_auto: update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL8Dialect